from __future__ import annotations

import sqlite3
import threading
from contextlib import AbstractContextManager
from typing import Any, Protocol


class StoreHost(Protocol):
    """Narrow structural boundary implemented by the V1Store compatibility facade."""

    policy: Any
    _schema_lock: threading.Lock

    def connect(self) -> sqlite3.Connection: ...

    def tx(self, *, immediate: bool = False) -> AbstractContextManager[sqlite3.Connection]: ...

    def get_project(self, project_id: str) -> dict[str, Any]: ...

    def get_task(self, task_id: str) -> dict[str, Any]: ...

    def get_project_task(self, project_id: str, task_id: str) -> dict[str, Any]: ...

    def get_workflow(self, project_id: str) -> dict[str, Any]: ...

    def get_workflow_revision(self, project_id: str, workflow_id: str) -> dict[str, Any]: ...

    def workflow_by_id(self, project_id: str, workflow_id: str) -> Any: ...

    def create_task(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

    def _dict(self, row: sqlite3.Row | None) -> dict[str, Any] | None: ...

    def _decode(self, row: dict[str, Any] | None, *fields: str) -> dict[str, Any] | None: ...

    def _pack_json(self, value: Any, *, max_bytes: int | None = None) -> str: ...

    def _event(self, db: sqlite3.Connection, project_id: str, task_id: str | None, run_id: str | None, event_type: str, data: dict[str, Any]) -> None: ...

    def _mailbox(self, db: sqlite3.Connection, project_id: str, event_type: str, task_id: str | None, run_id: str | None, payload: dict[str, Any]) -> None: ...

    def _refresh_projection(self, db: sqlite3.Connection, project_id: str) -> None: ...
